- pkg/ui/aim/embed/custom.patch
> Fix search on enter in Aim UI on Windows

- pkg/api/mlflow/dao/repositories/metric.go
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/FML-51) by [Unito](https://www.unito.io)
> MLFlow behaviour during metric logging

- pkg/api/mlflow/dao/models/param.go
- pkg/api/mlflow/dao/models/run.go
- pkg/api/mlflow/dao/repositories/param.go
- tests/integration/golang/fixtures/base.go
- tests/integration/golang/fixtures/run.go
- tests/integration/golang/mlflow/run/log_batch_test.go
- tests/integration/golang/mlflow/run/log_parameter_test.go
Fixes #43
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/FML-71) by [Unito](https://www.unito.io)
> Applying fixes from other branch here as patch

- pkg/api/mlflow/service/artifact/validators.go
- pkg/api/mlflow/service/artifact/validators_test.go
Even though we don't actually support artifacts yet, the MLFlow ListArtifacts endpoint was broken during the refactor and was returning an error instead of an empty list, resulting in an error message in the MLFlow UI. This PR fixes that.
Before:
After:
> Fix artifacts list

- pkg/cmd/decode.go
Example usage for development:
```sh
xh http://localhost:5000/aim/api/runs/search/run | go run main.go decode
```
> Add hidden 'decode' command

- .github/workflows/website.yml
using ` == 'true'` for comparison instead of literal
> fix website CI

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitignore
- .go-build-tags
- .vscode/launch.json
- .vscode/settings.json
- Dockerfile
- Makefile
- README.md
- docker-compose.yml
- docs/developer.md
- docs/quickstart.md
- tests/integration/python/aim/test.sh
- tests/integration/python/mlflow/test.sh
This PR adds a CI job to build the Go binaries for all the supported platforms and upload them as CI artifacts, enabling developers and users to try out a pull request, a branch, or a nightly build.
It also adds a CI job running after the CI has run for a tag that will create a GitHub release and upload the Go binaries to it.
The build produced by `make build` and the archive produced by `make dist` locally are the same as the ones produced by the CI.
The linux/arm64 and windows/x86_64 builds are cross-compiled from linux/x86_64 and the darwin/arm64 (macOS) is cross-compiled from darwin/x86_64. The reason for cross-compiling the Windows build is to speed up the CI (2 minutes instead of 6 minutes), as mingw is the only C compiler support by Go anyway.
All the Linux builds are …
> ci: build Go binaries and upload them to a release

- pkg/database/database.go
In #72 and #134, we introduced new database migrations. Unfortunately they had issues on SQLite 😞
#72 is recreating multiple tables twice, one of them being the one containing all the metrics, which takes quite a bit of time. This PR changes the migration to recreate the tables only once. Ideally we wouldn't need to recreate any tables, but this is a very unfortunate limitation of SQLite.
#134 is deleting all the run data (metrics, params, and tags) because the foreign key constraints were not disabled and the run table got recreated. This PR temporarily disables foreign key constraints for SQLite when running this particular migration to avoid the cascading delete.
> Fix database migrations that recreate table twice and delete run data on SQLite

- .github/workflows/release.yml
- python/setup.py
- Set README type to Markdown
- Only publish to PyPI for tags
> Python wheels fixes

- pkg/database/migrate.go
- pkg/database/postgres_db_instance.go
> Fix database migrations to be fully compatible with MLFlow on Postgres

- pkg/api/aim/query/query.go
- pkg/api/aim/runs.go
- pkg/api/aim/runs_test.go
> Improve logic for validating whether metrics are selected in the metrics explorer

- pkg/database/sqlite_db_instance.go
This had been fixed in #189, but was unfortunately reintroduced in #250 😞
> Fix (again) "database is locked" issue

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- docs/developer.md
This PR fixes our dev container config so that:
* existing volumes get their original name back
* ports are forwarded properly
* user is not encouraged to have a bad situation in terms of mounted volumes
The UI development guide is also improved and should work as-is in a dev container, or outside of a dev container. Hybrid is not supported!
> Fix dev container and improve UI development guide

- .devcontainer/docker-compose.yml
- README.md
- docs/quickstart.md
* Add `pip` instructions to README and quickstart docs
* Fix tracking sample
* Remove encryption information
* Improve developer section
> Improve README

- pkg/api/aim/query/query.go
- pkg/api/aim/query/query_test.go
Fixes #416.
Also reworked the query unit tests to be more readable and more focused on the actual query parsing.
> Add support for negative numbers in Aim query syntax

- .github/workflows/release.yml
- .github/workflows/website.yml
- website/docusaurus.config.js
- website/package.json
- website/yarn.lock
This PR changes how our website is built so that it fetches the latest release at build time and populates the announcement banner with it. It also triggers a website rebuild after a new release gets published.
> Automatically announce latest release on our website

- pkg/api/aim/request/metric.go
- tests/integration/golang/aim/metric/search_aligned_test.go
> Aim integration tests search aligned metrics 

- pkg/cmd/server.go
> Stop gracefully on SIGTERM

- pkg/database/sqlite_db_instance.go
The infamous DB refactor strikes again, this time borking the way we log the database URI.
Variables names have also been refactored to be more meaningful.
> Log the original SQLite database URI

- .github/workflows/check-required.yml
Follow-up on #458, #470, and #473.
> Create a pending required check as early as possible

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/website.yml
> [release/0.3] Restore functionality to update the website when a release is created

- .devcontainer/Dockerfile
- .github/workflows/ci.yml
- Makefile
This PR is the first in a series to address #328.
It's a collection of miscellaneous tooling improvements (CI, Makefile):
- Misc makefile improvements
- make lint should run all the linters
- Remove unnecessary stuff
- Add comments to keep tools versions in sync
> Miscellaneous tooling improvements

- pkg/api/mlflow/dao/models/experiment.go
- pkg/database/migrations/v_0006/model.go
- pkg/database/model.go
Our models are currently duplicated in multiple places in the code. This PR ensures that they are all in sync.
> Ensure our various copies of models are in sync

- tests/integration/golang/database/import_test.go
This PR improves our import tests to be more consistent with the style of our other tests (use of test suites).
It also checks for errors directly rather than assigning to `err` first, and it enforces that the calls to the row iterator return the same values.
> Improve the style of the import tests

- tests/integration/golang/helpers/gs.go
- tests/integration/golang/helpers/s3.go
- tests/integration/golang/mlflow/artifact/get_artifact_s3_test.go
- tests/integration/golang/mlflow/artifact/list_s3_test.go
- tests/integration/golang/mlflow/namespace/flows/artifact_test.go
This is a little cosmetic PR to improve the consistency between our GCP and S3 test helpers.
> Improve consistency between bucket storage provider test helpers

- tests/integration/golang/aim/experiment/get_experiment_test.go
- tests/integration/golang/aim/experiment/get_experiments_test.go
- tests/integration/golang/aim/project/get_project_test.go
- tests/integration/golang/aim/run/get_run_info_test.go
- tests/integration/golang/mlflow/artifact/list_gs_test.go
- tests/integration/golang/mlflow/artifact/list_s3_test.go
- tests/integration/golang/mlflow/experiment/create_test.go
- tests/integration/golang/mlflow/experiment/get_by_name_test.go
- tests/integration/golang/mlflow/experiment/get_test.go
- tests/integration/golang/mlflow/metric/get_histories_test.go
- tests/integration/golang/mlflow/run/delete_tag_test.go
- tests/integration/golang/mlflow/run/delete_test.go
- tests/integration/golang/mlflow/run/get_test.go
This PR is a grab bag of little fixes/improvements to the integration tests:
* some responses were not correctly validated
* some errors were checked twice
* some typos in test names and comments
* some inconsistent formatting
> Miscellaneous improvements to integration tests

- python/setup.py
> [release/0.4] Fix Python version incompatibilities with semantic versioning

- pkg/common/middleware/namespace/namespace.go
This PR gets rid of some duplicated code in the namespace middleware.
> DRY up the namespace middleware

- pkg/api/aim/runs.go
- tests/integration/golang/aim/run/get_run_info_test.go
- tests/integration/golang/aim/run/get_runs_active_test.go
- tests/integration/golang/aim/run/search_test.go
- tests/integration/golang/fixtures/run.go
> [release/0.4] Fix experiment name not being displayed in Aim UI run views

- tests/integration/golang/aim/app/delete_app_test.go
- tests/integration/golang/aim/app/get_app_test.go
- tests/integration/golang/aim/app/update_app_test.go
- tests/integration/golang/aim/dashboard/create_dashboard_test.go
- tests/integration/golang/aim/dashboard/delete_dashboard_test.go
- tests/integration/golang/aim/dashboard/get_dashboard_test.go
- tests/integration/golang/aim/dashboard/get_dashboards_test.go
- tests/integration/golang/aim/dashboard/update_dashboard_test.go
- tests/integration/golang/database/import_test.go
- tests/integration/golang/fixtures/app.go
- tests/integration/golang/fixtures/dashboard.go
This PR removes a lot of unnecessary boilerplate to create apps and dashboards in our integration tests.
> Simplify app and dashboard creation in integration tests

- pkg/database/migrate.go
- pkg/database/migrations/v_0008/migrate.go
- pkg/database/migrations/v_0008/model.go
> [release/0.4] Fix default namespace bookmarks disappearing after migration

- pkg/api/aim/response/app.go
- pkg/api/aim/response/dashboard.go
- tests/integration/golang/aim/app/get_apps_test.go
- tests/integration/golang/aim/dashboard/create_dashboard_test.go
- tests/integration/golang/aim/dashboard/get_dashboard_test.go
- tests/integration/golang/aim/dashboard/get_dashboards_test.go
- tests/integration/golang/aim/dashboard/update_dashboard_test.go
- tests/integration/golang/aim/namespace/flows/app_test.go
- tests/integration/golang/aim/namespace/flows/dashboard_test.go
> [release/0.4] Improve the response types used for apps and dashboards in integration tests

- tests/integration/golang/aim/app/delete_app_test.go
- tests/integration/golang/aim/app/get_app_test.go
- tests/integration/golang/aim/app/update_app_test.go
- tests/integration/golang/aim/dashboard/create_dashboard_test.go
- tests/integration/golang/aim/dashboard/delete_dashboard_test.go
- tests/integration/golang/aim/dashboard/get_dashboard_test.go
- tests/integration/golang/aim/dashboard/get_dashboards_test.go
- tests/integration/golang/aim/dashboard/update_dashboard_test.go
- tests/integration/golang/database/import_test.go
- tests/integration/golang/fixtures/app.go
- tests/integration/golang/fixtures/dashboard.go
> [release/0.4] Simplify app and dashboard creation in integration tests

- go.mod
- go.sum
Brings Aim UI change https://github.com/G-Research/fasttrackml-ui-aim/pull/27.
Fixes #715.
> Make Aim UI local storage keys namespaced

- go.mod
- go.sum
> [release/0.4] Make Aim UI local storage keys namespaced

- pkg/api/aim/runs.go
> [release/0.5] Fix GetRunMetrics endpoint.

- pkg/database/migrations/v_0009/migrate.go
> metric primary keys have different names when migrated from mlflow

- python/fasttrackml/_tracking_service/client.py
Backport of https://github.com/G-Research/fasttrackml/pull/996.
Fixes https://github.com/G-Research/fasttrackml/issues/975.
> [release/0.5] Fix credentials in Python Client

- python/fasttrackml/_tracking_service/client.py
- python/pyproject.toml
Backport of https://github.com/G-Research/fasttrackml/pull/1081.
Fixes https://github.com/G-Research/fasttrackml/issues/1080.
> [release/0.5] Update creds import in python client

- go.mod
- go.sum
Backport of https://github.com/G-Research/fasttrackml/pull/1100.
> [release/0.6] Update Aim UI tag ref

- pkg/api/mlflow/dao/repositories/metric.go
- tests/integration/golang/mlflow/run/log_batch_test.go
#1108 Fix failing batch logging on sqlite
> mlflow: fixed log-batch limit reached with sqlite

- docs/example/k6_load.js
This PR updates the k6 load script to make it work with the frontend E2E test pipeline which expects images being logged (https://github.com/G-Research/fasttrackml-ui-aim/pull/115).
> Add image logging to k6 load script

- .github/workflows/release.yml
@jgiannuzzi any pointers on how to test this?
Is this something I can do locally? If so, what values really matter here and which could dummy?
> Attempt to add multiarch digest
