G-Research/fasttrackml

- pkg/database/database.go
- pkg/database/model.go
I forgot to ensure the new `runs.row_num` and `metrics.iter` fields were indexed. This update should increase query speed in a few operations.
> Create database indices on recently added fields

- pkg/api/aim/projects.go
- pkg/api/aim/query/query.go
- pkg/api/aim/runs.go
MLFlow tags are now exposed in Aim UI as a param object named `tags`.
We'll probably want to rename Aim tags to labels (which they are, really) everywhere in the UI before we add support for those.
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/FML-48) by [Unito](https://www.unito.io)
> Expose MLFlow tags in Aim UI

- .github/dependabot.yml
To avoid being spammed, I suggest enabling only security updates for the website.
> Keep only security updates for website dependencies

- pkg/api/mlflow/dao/models/run.go
- pkg/database/model.go
Fixes #108.
Since the refactor, we are now trying to update too many fields in multiple places (e.g. in `UpdateRun`). This is because we used to update only the required fields but we now pass around pointers to `Run` objects.
I chose to solve this by marking the fields as create+read in Gorm annotations.
> Fix offset issue in Aim API GetExperimentRuns

- pkg/api/mlflow/dao/repositories/metric.go
`GetMetricsHistories` currently panics with the following stacktrace:
```
panic: reflect: reflect.Value.Set using unaddressable value
goroutine 35 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/gofiber/fiber/v2/middleware/recover.defaultStackTraceHandler(0x40004da900, {0x12d2780, 0x4000222410})
/go/pkg/mod/github.com/gofiber/fiber/v2@v2.47.0/middleware/recover/recover.go:12 +0x28
github.com/gofiber/fiber/v2/middleware/recover.New.func1.1()
/go/pkg/mod/github.com/gofiber/fiber/v2@v2.47.0/middleware/recover/recover.go:31 +0x88
panic({0x12d2780, 0x4000222410})
/usr/local/go/src/runtime/panic.go:890 +0x21c
reflect.flag.mustBeAssignableSlow(0x97)
/usr/local/go/src/reflect/value.go:262 +0x9c
reflect.flag.mustBeAssignable(0x97) …
```
> Fix broken GetMetricsHistories endpoint

- .github/workflows/release.yml
This is to avoid shell injection attacks by committers.
> Stricter handling of tag name in release workflow

- tests/integration/golang/aim/experiment/delete_test.go
- tests/integration/golang/mlflow/run/log_batch_test.go
Integration tests are currently broken when using the SQLite backend. This PR fixes that.
> Fix integration tests with SQLite backend

- pkg/api/mlflow/dao/repositories/experiment.go
- pkg/database/database.go
For performance reasons, we used to configure 4 write connections to SQLite, but this can introduce "database is locked" errors when under write load. It's better to be safe and using only 1 write connection is the supported way to write to SQLite as it avoids any concurrency.
Once we start using DuckDB (#85) as our default backend, we'll get much better write performance, especially on concurrent workloads. Users that need better concurrency performance can already use the PostgreSQL backend.
> Fix "database is locked" issue with SQLite

- .golangci.yml
- .vscode/settings.json
This is first step towards addressing #213. The `golangci-lint` configuration is slightly adapted to include the linters already used in the CI pipeline, and the linting is also enabled in VSCode to help devs catch issues during development.
> Improve linter configuration

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .github/workflows/ci.yml
- .gitignore
- Dockerfile
- docker-compose.yml
- go.mod
- go.sum
- pkg/api/mlflow/service/artifact/service_test.go
- pkg/api/mlflow/service/experiment/service_test.go
- pkg/api/mlflow/service/metric/service_test.go
- pkg/api/mlflow/service/run/service_test.go
- Upgrade devcontainer to Debian bookworm
- Upgrade mockery from 2.30.16 to 2.32.4
- Upgrade golangci-lint from 1.53.3 to 1.54.1
- Use context directly in unit tests as mocking depends on Go internals that changed in Go 1.21
> Upgrade Go from 1.20 to 1.21

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- .vscode/settings.json
- Makefile
- Pipfile
- Pipfile.lock
- docs/example/random_forest.py
- python/batch.py
- Add pipenv basic environment with mlflow, black, and isort
- Install black and isort VS Code extensions
- Setup VS Code for automatic Python formatting
- Add Makefile targets for formatting and linting
- Add Python linting to CI
- Format Python files
> Python formatting and linting

- pkg/database/migrate.go
MLFlow 2.3.0 introduced a new alembic schema version `3500859a5d39` which only adds tables used by the model versioning server, which we don't implement. We however need to know about this schema version in order to be compatible with MLFlow databases used with this version of MLFlow.
MLFlow 2.4.0 introduced `7f2a7d5fae7d` which only adds tables used by the new dataset tracking feature, which we don't implement either. This schema version is used up to at least MLFlow 2.6.0 (at the time of writing of this PR).
> Add database migrations support for MLFlow 2.3.0 to 2.6.0

- pkg/cmd/root.go
* Use actual binary name in help output
* Improved description in help output
* Use full project name in version output
* Fix linting issue in `pkg/cmd/root.go`
Before:
```
$ ./fml
FastTrackML is a rewrite of the MLFlow tracking server with a focus on scalability.
It aims at being 100% compatible with the MLFlow client library and should be a
drop-in replacement. It can even use existing SQLite/SQLCipher/PostgreSQL
databases created by MLFlow 1.21+.
Usage:
fml [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
help        Help about any command
import      Copies an input database to an output database
server      Starts the tracking server
Flags:
-h, --help               help for fml
-l, --log-level string   Log level (default "info")
-v, …
```
> Improve help and version outputs

- pkg/database/postgres_db_instance.go
- pkg/database/sqlite_db_instance.go
#250 introduced a regression by removing the connection pool settings from our Postgres backend. This PR fixes it, and also wraps all the database creation errors with `eris.Wrap`.
> Fix Postgres connection pool regression

- pkg/api/aim/query/clause.go
- pkg/api/aim/query/query_test.go
Fixes #414.
There are also a few minor changes:
- an unnecessary call to `fmt.Sprintf` was removed
- SQL expressions have been made uppercase for consistency
- a few linting issues have been "fixed" by ignoring them as we stick to the Gorm conventions
I didn't add test cases to the integration tests to avoid merge conflicts with `features/namespaces`, but we should definitely cover this — see https://github.com/G-Research/fasttrackml/issues/414#issuecomment-1744744382 for how to reproduce.
> Fix issue with searching for metric names via regex

- website/docusaurus.config.js
This PR changes the announcement bar `id` to be dynamic, so than when the bar has been dismissed for a past release, it appears again when there is a new release.
> Add dynamic id to website announcement bar

- pkg/api/aim/runs.go
Fixes #435.
I didn't update integration tests for this one because too many things have changed in the `features/namespaces` branch. I will create a separate issue about testing NaNs everywhere it makes sense.
> Fix NaN json serialization in Aim `GetRunMetrics`

- .github/workflows/ci.yml
- .github/workflows/create.yml
- .github/workflows/release.yml
- docs/maintainer.md
This PR changes the CI release logic in the following way:
* add a workflow `create.yml` to create release branches and tags in a controlled manner, using a GitHub app that will have exceptions in the rulesets
* change the `release.yml` workflow to be directly called by the main CI workflow
* change `release.yml` to not validate the ref anymore, but instead rely on rulesets and environments
* add support for prereleases
* document workflow in `docs/maintainer.md`
---
The following tasks need to be completed before merging this PR (more information can be found in the documentation):
---
Examples on a repo that has been setup as described and as "upstream" (so _not_ a fork, but in this case a copy):
> [!NOTE]
> Many of these links may require to be reloaded before they display the actual …
> Change CI release logic

- .github/workflows/check-required.yml
This PR improves how we create the required check "All required checks succeeded" in the following ways:
* We now use a GitHub app to create the check instead of using the token provided by GitHub Actions.
This allows us to create the check run with its own check suite instead of attaching it to the first GHA check suite, which changes when a pull request is closed and reopened, or when a new run attempt is made. See https://github.com/orgs/community/discussions/24616#discussioncomment-6088422 for more details on this very annoying GitHub limitation.
* A check is created and set as `queued` or `in_progress` when the corresponding workflow run's status changes.
This is needed so that the check is reset when a new run attempt is made or a PR is reopened.
* Logging is improved.
* …
> Improve required checks creation in CI

- .github/workflows/create.yml
- .github/workflows/release.yml
- docs/maintainer.md
This PR builds on #452 and goes one step further to automatically create the corresponding release branch when we bump the minor version. The original reasoning was to enforce some form of manual validation to avoid bumping the minor version by mistake. However GitHub released yesterday the ability to [prevent self-review in secure deployments](https://github.blog/changelog/2023-10-16-actions-prevent-self-reviews-for-secure-deployments-across-actions-environments/) which means we can now gate the release creation behind a proper approval.
Creating a release now looks like this (can't really make it simpler 😄):
---
This PR requires the following task before merging:
> Create release branches automatically during tag creation

- .github/workflows/check-required.yml
#458 introduced the use of a GitHub environment and a GitHub app to implement the required checks. On repo forks, these will most likely not exist, and the need for any kind of required checks is probably close to zero.
This PR is thus disabling the required checks creations on forks.
> Do not run "Check required jobs" on forks

- .github/workflows/check-required.yml
We were looking for the corresponding workflow runs, which could cause all kinds of race conditions. We now always get the latest info from the API instead of relying on what we received, which might be out of date by the time we actually run.
Here is the example of a dependabot pull request, which essentially creates 2 different runs (one for the `pull_request` event and one for the `push` event). The `pull_request` event results in a skipped run, and the `push` event eventually succeeds.
1. when the `check-required.yml` workflow runs for the first time, its summary looks like this:
2. the check it creates looks like this:
3. when the `push` event run eventually succeeds, the `check-required.yml` workflow run that gets triggered looks like this:
5. and the resulting check looks like …
> Rewrite the required checks process to look for check runs of the commit

- .github/dependabot.yml
- Pipfile
- Pipfile.lock
* Update Python dependencies
* Move dependencies that are not required to run `lint` or `dist` to `dev-packages` (installable with `pipenv sync --dev`)
* Enable Dependabot to automate this in the future
> Python dependencies maintenance

- .github/workflows/ci.yml
This will help us remember running `go mod tidy` before merging anything.
Example run with failure here: https://github.com/jgiannuzzi/fasttrackml/actions/runs/6560857545
> Check module files in CI

- pkg/cmd/server.go
Backport of #476 to `release/0.3`. Fixes #445.
> [release/0.3] Stop gracefully on SIGTERM

- pkg/api/aim/runs.go
The Aim UI knows how to deal with such values but we were not mapping them correctly in the encoded result, as MLFlow's database storage uses MaxFloat64 instead of infinity. This PR adds a mapping back from MaxFloat64 to proper infinity.
Fixes #489
> Fix wrong Y axis scale in Aim UI when metric has infinity values

- pkg/api/aim/runs.go
> [release/0.3] Fix wrong Y axis scale in Aim UI when metric has infinity values

- tests/integration/golang/helpers/s3.go
- tests/integration/golang/mlflow/artifact/get_artifact_s3_test.go
- tests/integration/golang/mlflow/artifact/list_s3_test.go
…t bucktes instead of to use global ones.
> Improve S3 `CreateBuckets` and `RemoveBuckets` test helper functions.

- tests/integration/docker-compose.yml
For the latest `minio/minio:latest` image `health` check just started failing. It happened, because they started using another `base` image without `curl`. Workaround is here -> https://github.com/minio/minio/issues/18373#issuecomment-1790003599
> Fix health check for minio service in integration tests

- .github/workflows/ci.yml
- pkg/api/aim/projects.go
- pkg/api/aim/runs.go
- tests/integration/python/aim/custom.patch
- tests/integration/python/aim/test.sh
This PR is the fifth in a series to address #328.
It makes the Aim Python integration tests setup lighter by ditching the unused Aim fixtures. It also makes them more accurate by fixing the server rather than the tests. Finally, it enables more tests that were previously skipped.
> Improve Aim Python integration tests

- tests/integration/docker-compose.yml
> [release/0.3] Fix health check for minio service in integration tests

- pkg/api/mlflow/dao/repositories/helpers.go
- pkg/api/mlflow/dao/repositories/helpers_test.go
- pkg/api/mlflow/dao/repositories/param.go
- pkg/api/mlflow/service/run/service.go
- pkg/api/mlflow/service/run/service_test.go
- tests/integration/golang/fixtures/param.go
- tests/integration/golang/mlflow/run/log_batch_test.go
- tests/integration/golang/mlflow/run/log_parameter_test.go
* Rely on database to detect duplicate parameter logging where the value has changed and prevent them
* Fail the entire batch when an invalid duplicate parameter is detected
* Return HTTP 400 instead of 500 in case of duplication
Backport of #550.
Fixes #523.
> [release/0.3] Permit duplicate param logging

- pkg/api/mlflow/service/artifact/service_test.go
- tests/integration/golang/database/migrate_test.go
- tests/integration/golang/mlflow/artifact/get_artifact_s3_test.go
- tests/integration/golang/mlflow/metric/get_histories_test.go
- tests/integration/golang/mlflow/metric/get_history_bulk_test.go
- tests/integration/golang/mlflow/metric/get_history_test.go
- tests/integration/golang/mlflow/namespace/flows/artifact_test.go
- tests/integration/golang/mlflow/namespace/flows/experiment_test.go
- tests/integration/golang/mlflow/namespace/flows/metric_test.go
- tests/integration/golang/mlflow/namespace/flows/run_test.go
- tests/integration/golang/mlflow/namespace/namespace_test.go
- tests/integration/golang/mlflow/run/create_test.go
- tests/integration/golang/mlflow/run/delete_test.go
- tests/integration/golang/mlflow/run/get_test.go
- tests/integration/golang/mlflow/run/log_parameter_test.go
- tests/integration/golang/mlflow/run/restore_test.go
- tests/integration/golang/mlflow/run/set_tag_test.go
- tests/integration/golang/mlflow/run/update_test.go
Same logic as #584. Implemented again following some changes made in #582.
> Use `require` instead of `assert` for checking errors in tests

- pkg/database/migrations/v_0001/model.go
- pkg/database/migrations/v_0002/model.go
- pkg/database/migrations/v_0003/model.go
- pkg/database/migrations/v_0004/model.go
- pkg/database/migrations/v_0005/model.go
A little mistake slipped into the `v_0003` historical model and it ended up with the namespace changes. This PR fixes that.
All non-DB-related code has also been unified between the historical models to ease their comparison.
> Fix v_0003 historical model and unify non-DB code between historical models

- pkg/api/mlflow/dao/models/experiment.go
- pkg/database/migrations/v_0006/migrate.go
- pkg/database/migrations/v_0006/model.go
- pkg/database/model.go
Fixes #567 by using a proper composite index that relies on Gorm's naming strategy instead of a hardcoded one.
> DB schema: rename experiments unique index

- pkg/api/aim/response/run.go
- tests/integration/golang/aim/app/create_app_test.go
- tests/integration/golang/aim/app/get_apps_test.go
- tests/integration/golang/aim/run/get_run_info_test.go
- tests/integration/golang/aim/run/get_runs_active_test.go
This PR corrects the types used by timestamps in our Aim integration tests. We were incorrectly using integers whilst the API is returning floats. A couple of disabled assertions are also enabled.
> Fix timestamp types in Aim integration tests

- tests/integration/golang/database/migrate_test.go
This PR improves the migration tests to use the same style as all our other tests: using a test suite and sub tests.
This means that if one migration fails but not the others, we will see it in the results, instead of having the entire test fail and not try the other migration(s).
> Use a consistent test style in migration tests

- pkg/api/admin/service/namespace/service.go
When creating a new namespace, the default experiment under that namespace should be named "Default".
> Default experiments should be named "Default"

- pkg/cmd/decode.go
What's inside the box:
- `stream` decode command output now formatted.
Fixes #515.
> Improve the output of the hidden `decode` command

- python/setup.py
We recently released `0.4.0-rc.1`, but the Python wheels could not get uploaded to PyPI because the Python version specifier spec is incompatible with semantic versioning. This PR fixes that.
Once merged, the following tasks need to happen:
> Fix Python version incompatibilities with semantic versioning

- pkg/api/mlflow/dao/repositories/namespace_cached.go
We were erroneously using the `fiber` logger instead of the `logrus` one in `NamespaceCachedRepository`.
> Use the correct logger in NamespaceCachedRepository

- tests/integration/golang/mlflow/namespace/flows/run_test.go
This test assumed that the ordering of the tags, params, and metrics was guaranteed by the server, but it isn't. This PR changes the way we check for slice equality to allow for any order.
> Fix flaky Run flow integration test

- .github/workflows/ci.yml
- .vscode/launch.json
- Makefile
- tests/integration/docker-compose.yml
- tests/integration/golang/helpers/client.go
- tests/integration/golang/helpers/test.go
This PR changes our integration tests to have a new unique server instance per test, allowing us to debug end-to-end and simplifying the setup.
> Create a new server instance per test in the integration tests

- Makefile
- tests/integration/docker-compose.yml
- tests/integration/golang/helpers/env.go
- tests/integration/golang/helpers/test.go
This PR ensures that logging is configured in our integration tests using the expected `FML_LOG_LEVEL` environment variable. The `Makefile` targets are also updated so that the debug logs are only displayed when a test fails.
> Hook up logging in integration tests

- .github/workflows/ci.yml
- Makefile
- tests/integration/docker-compose.yml
- tests/integration/golang/database/import_test.go
- tests/integration/golang/helpers/database.go
- tests/integration/golang/helpers/env.go
- tests/integration/golang/helpers/test.go
- tests/integration/golang/mlflow/namespace/flows/artifact_test.go
This PR changes the integration test setup so that a new temporary database is created per test, which allows us to run all the test packages in parallel.
> Parallelize integration tests

- pkg/api/mlflow/dao/repositories/mock_namespace_repository_provider.go
- pkg/api/mlflow/dao/repositories/namespace.go
- pkg/api/mlflow/dao/repositories/namespace_cached.go
- pkg/common/middleware/namespace/namespace.go
- tests/integration/golang/helpers/client.go
This PR reverts our temporary solution that disabled caching in our integration tests now that we use per-test embedded server instances.
> Revert the temporary solution of disabling cache for integration tests

- pkg/api/aim/runs.go
- tests/integration/golang/aim/run/get_run_info_test.go
- tests/integration/golang/aim/run/get_runs_active_test.go
- tests/integration/golang/aim/run/search_test.go
- tests/integration/golang/fixtures/run.go
Our latest release inadvertently removed experiment names from the all Aim UI run views. This PR fixes it and adds a few additional assertions to our integration tests.
> Fix experiment name not being displayed in Aim UI run views

- .github/dependabot.yml
This PR configures Dependabot to group all the `github.com/aws/aws-sdk-go-v2` updates in a single pull request instead of the usual 3.
> Group Dependabot AWS SDK pull requests

- pkg/api/aim/response/app.go
- pkg/api/aim/response/dashboard.go
- tests/integration/golang/aim/app/get_apps_test.go
- tests/integration/golang/aim/dashboard/create_dashboard_test.go
- tests/integration/golang/aim/dashboard/get_dashboard_test.go
- tests/integration/golang/aim/dashboard/get_dashboards_test.go
- tests/integration/golang/aim/dashboard/update_dashboard_test.go
- tests/integration/golang/aim/namespace/flows/app_test.go
- tests/integration/golang/aim/namespace/flows/dashboard_test.go
This PR changes the response types used for apps and dashboards to use proper UUID types. It also renames the `app_type` field and checks it in the various dashboard tests.
> Improve the response types used for apps and dashboards in integration tests

- pkg/database/migrations/v_0007/migrate.go
Backport of #713.
Remove `RunWithoutForeignKeyIfNeeded` no-op in `v_0007` migration.
> [release/0.4] Cleanup of some recent database migrations

- pkg/api/aim/dashboards.go
- tests/integration/golang/aim/dashboard/get_dashboards_test.go
This PR changes `GetDashboards` to sort the results by `App.UpdateAt` in reverse chronological order.
Fixes #728.
> List most recent bookmarks on top

- Makefile
Fixes #746 by implementing a fallback version identifier when no tags are present.
Also cleans up some unnecessary variables and comments in the Makefile.
> Fallback to a Python-compatible version identifier when no tags are present

- .github/workflows/ci.yml
- .github/workflows/release.yml
Bump [`actions/download-artifact`](https://github.com/actions/download-artifact/tree/v4) and [`actions/upload-artifact`](https://github.com/actions/upload-artifact/tree/v4) from 3 to 4, which introduced [breaking changes](https://github.com/actions/upload-artifact/tree/v4#breaking-changes). We now explicitly upload different artifacts with different names and join them back together at download time.
This PR supersedes #751 and #752.
> Bump actions/download-artifact and actions/upload-artifact from 3 to 4

- .github/actions/setup-go/action.yml
We are currently getting deprecation warnings in our CI:
This PR solves them via:
* Bump `actions/setup-go` from `v4` to `v5`
* Bump `actions/cache` from `v3` to `v4`
These 2 actions didn't get updated by Dependabot automatically, hence the manual update.
> Bump actions used by `setup-go` to use Node 20

- pkg/database/migrations/v_0009/migrate.go
* Separate migration approaches for Sqlite and Postgres for metric context -- for Postgres, we alter tables to add context_id, but for Sqlite we create anew. This allows the Postgres migration to run quickly on large data.
---------
> Alter context migration for Postgres efficiency (#941)

- pkg/api/aim2/dao/repositories/experiment.go
Backend PR for https://github.com/G-Research/fasttrackml/issues/1054 to ensure that experiments are ordered by `experiment_id`.
Frontend PR: https://github.com/G-Research/fasttrackml-ui-aim/pull/57
> Ensure experiments are ordered by id

- Makefile
The runner image for `ubuntu-22.04` has removed `docker-compose` in version `20240401.4.0` and it's [breaking our CI](https://github.com/G-Research/fasttrackml/actions/runs/8532040048/job/23372600776#step:1:9).
This PR fixes this by letting go of the deprecated `docker-compose` syntax in favour of `docker compose`.
> Use Docker Compose v2 for container-based tests

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
https://github.com/devcontainers/features/issues/745 finally fixed the `docker-in-docker` devcontainer feature to use Docker Compose v2. Our workaround that was [installing it manually in the `Dockerfile`](https://github.com/G-Research/fasttrackml/blob/da0d04501eed0ce6351702f3751947ba789fec23/.devcontainer/Dockerfile#L43-L45) became obsolete, but it unfortunately broke the devcontainer. #1029 tried to fix it by pinning to an older version of the feature. This PR is proper fix that allows us to use a more recent version of the feature.
> Update `docker-in-docker` devcontainer feature and let go of workaround

- .github/workflows/ci.yml
The cache key was not computed correctly for the Go integration tests in our CI since #687. This PR fixes that.
> chore: CI - Fix cache key computation in Go integration tests

- docs/developer.md
- docs/example/k6_load.js
- pkg/api/mlflow/dao/repositories/run.go
@jgiannuzzi's k6 load test script, with a few tweaks for configuring the shape.
> Add the k6 load test script to the docs

- .github/workflows/release.yml
- .gitignore
- docs/quickstart.md
- helm/fasttrackml/.helmignore
- helm/fasttrackml/Chart.yaml
- helm/fasttrackml/templates/_helpers.tpl
- helm/fasttrackml/templates/configMap.yaml
- helm/fasttrackml/templates/deployment.yaml
- helm/fasttrackml/templates/ingress.yaml
- helm/fasttrackml/templates/service.yaml
- helm/fasttrackml/templates/tests/test-connection.yaml
- helm/fasttrackml/values.yaml
The goal of this PR is to package FastTrackML and allow contributors to also use it inside a Kubernetes cluster with simple installation
The scope of change includes
```bash
git checkout oss-350-helm-chart-lvl-2
kind create cluster --name fastrackml
kubectl cluster-info --context kind-fastrackml
helm install fasttrackml ./helm/fasttrackml
kubectl port-forward deployment/fasttrackml 5000:5000
kind delete cluster --name fastrackml
```
In your local browser at http://localhost:5000 service will be exposed
Resolves: https://github.com/G-Research/oss-portfolio-maturity/issues/350
> Helm chart - fasttrackml

- .github/workflows/ci.yml
This PR fixes the missing part from the name of `python-integration-tests` job names. `api` was being picked up from the matrix, which doesn't exists, which made github print out empty parenthesis in the job name. Matrix defines 'test-targets' instead. 
Ran into this accidentally, saw an opportunity and fixed it (boy scout rule).
Working example: https://github.com/pavlovic-ivan/fasttrackml/actions/runs/9207382745
> Fix python-integration-tests name

- pkg/api/aim/dao/repositories/tag.go
- pkg/api/aim/services/run/service.go
- pkg/server/server.go
Fixes https://github.com/G-Research/fasttrackml/issues/373.
When we receive a description during a run update, we create a new run tag with key `mlflow.note.content` which is the way MlFlow uses to store the run description
> Store the Run Description as a tag

- .github/workflows/ci.yml
- .github/workflows/release.yml
See https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds
> Add Attestations

- README.md
- website/docusaurus.config.js
We wish to lure FastTrackML users to our new https://github.com/mlflow/mlflow-go-backend project.
@naskio did I got that website setting right?
> Mention mlflow-go

- .github/workflows/release.yml
We use reusable workflows, which clash with PyPI attestations, so we have to disable them (we never used them and they got introduced in a newer version of the PyPI publishing action we use).
> Disable PyPI attestations as they prevent publishing to PyPI
